# Generated by Django 4.1.7 on 2023-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='available_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
