# Generated by Django 4.1.7 on 2023-10-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obrok', '0003_donation_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='obrok.restaurant'),
        ),
    ]
